import type { Metadata } from 'next';
import localFont from 'next/font/local';

import { Navigation } from '@/features/navigation';
import { ThemeProvider } from '@/features/theming';
import ReduxProvider from '@/redux/ReduxProvider';

import classes from '../styles/rootLayout.module.scss';
import '../styles/globals.scss';

const openSans = localFont({
  src: [
    {
      path: '../../public/fonts/OpenSans-Regular.woff2',
      weight: '100 400',
      style: 'normal',
    },
    {
      path: '../../public/fonts/OpenSans-Bold.woff2',
      weight: '500 900',
      style: 'normal',
    },
  ],
  variable: '--font-open-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${openSans.variable}`}>
        <ReduxProvider>
          <ThemeProvider>
            <header>
              <Navigation className={classes['root-layout__navigation']} />
            </header>
            <main className={classes['root-layout__main']}>{children}</main>
          </ThemeProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
